### ISSUE TITLE
[Feature] 좋아요 조회 관련 API 추가

### ISSUE THREAD

**Issue by jwooo** [jisung-in/backend#104]
## 📑 작업 사항
좋아요 관련 API 추가

## To-do
- [ ] `TalkRoom` 좋아요 API 추가 및 분리
- [ ] `Comment` 좋아요 API 추가 및 분리
- [ ] `Review` 좋아요 API 추가

## ETC
