### ISSUE TITLE
[Feature] 나의 토크방 모아보기 API 구현

### ISSUE THREAD

**Issue by AHNYUNKI** [jisung-in/backend#105]
## 📑 작업 사항
나의 토크방 모아보기 API 구현

## To-do
- [ ] 나의 토크방 모아보기 API 구현
- [ ] 나의 토크방 모아보기 API 테스트 코드 작성
- [ ] 나의 토크방 모아보기 API REST Docs 작성

## ETC
