### ISSUE TITLE
[Refactor] TalkRoom API 리펙토링 

### ISSUE THREAD

**Issue by AHNYUNKI** [jisung-in/backend#20]
## 📑 작업 사항
TalkRoom API 리펙토링

## To-do
- [ ] TalkRoom title 필드 추가
- [ ] TalkRoom Book title 필드 추가
- [ ] TalkRoom 유저 @Auth 어노테이션 추가

## ETC
