### ISSUE TITLE
[Test] Book API 테스트 수정

### ISSUE THREAD

**Issue by jwooo** [jisung-in/backend#27]
## 📑 작업 사항
- #25 에서 발생한 테스트 코드 수정
- API 테스트 `@SpringBootTest`에서 `@WebMvcTest`로 변경

## To-do
- [x] `BookServiceTest`에서 발생한 테스트 코드 수정
- [x] API 변경으로 인한 테스트 코드 수정
- [x] API 테스트 `@WebMvcTest`로 변경

## ETC
