### ISSUE TITLE
[Feature] TalkRoom Comment 수정, 삭제 API 구현

### ISSUE THREAD

**Issue by AHNYUNKI** [jisung-in/backend#38]
## 📑 작업 사항
TalkRoom Comment 수정, 삭제 API 구현

## To-do
- [ ] TalkRoom Comment 수정 API 구현
- [ ] TalkRoom Comment 수정 API 테스트 코드 작성
- [ ] TalkRoom Comment 삭제 API 구현
- [ ] TalkRoom Comment 수정 API 테스트 코드 작성

## ETC
