### ISSUE TITLE
[Feature] TalkRoom 좋아요, 검색 쿼리 기능 구현

### ISSUE THREAD

**Issue by AHNYUNKI** [jisung-in/backend#40]
## 📑 작업 사항
TalkRoom 좋아요, 검색 쿼리 기능 구현

## To-do
- [x] TalkRoom 좋아요 구현
- [x] TalkRoom 좋아요 테스트 작성
- [x] TalkRoom 검색 쿼리 구현
- [x] TalkRoom 검색 쿼리 테스트 코드 작성

## ETC
