### ISSUE TITLE
[Refactor] TalkRoom 조회 Query 리펙토링

### ISSUE THREAD

**Issue by AHNYUNKI** [jisung-in/backend#61]
## 📑 작업 사항
TalkRoom 조회 Query 리펙토링

## To-do
- [x] TalkRoom 조회 API Query 분리
- [x] TalkRoom 조회 시 검색, 정렬 조건 분리
- [x] TalkRoom 조회 API, Comment 조회 API 분리

## ETC
