### ISSUE TITLE
[Feature] 의견 등록 시 이미지 업로드 기능 추가

### ISSUE THREAD

**Issue by AHNYUNKI** [jisung-in/backend#80]
## 📑 작업 사항
의견 등록 시 이미지 업로드 기능 추가

## To-do
- [x] 의견 등록 시 이미지 업로드 기능 추가
- [x] 의견 등록 시 이미지 업로드 테스트 코드 추가
- [x] REST docs 테스트 작성

## ETC
